Narrow the return type of bind,unbind,try_unbind,new in subclass
This narrows the return type of `bind`,`unbind`,`try_unbind` and `new`
in `FilteringBoundLogger` to return `FilteringBoundLogger` instead of
`BindableLogger`. This makes it easier to use structlog in a typed
context like this:

```python
def typecheck_filtering_return() -> None:
    fblogger: FilteringBoundLogger = structlog.get_logger(__name__)
    fblog = fblogger.bind(key1="value1", key2="value2", key3="value3")
    fblog.info("values bound")
    fblog = fblog.unbind("key1")
    fblog.debug("value unbound")
    fblog = fblog.try_unbind("bad_key")
    fblog.warn("no value unbound because key not defined")
    fblog = fblog.new(new="value")
    fblog.info("this is a whole new logger")
```

Without this change the above example will result in a type
error when using `mypy --strict` as the type of `fblog` will be `BindableLogger`
which does not have an `info` method:

```console
typing_examples.py:288: error: "BindableLogger" has no attribute "info"
typing_examples.py:290: error: "BindableLogger" has no attribute "debug"
typing_examples.py:292: error: "BindableLogger" has no attribute "warn"
typing_examples.py:294: error: "BindableLogger" has no attribute "info"
Found 4 errors in 1 file (checked 19 source files)
```